# Site settings
title: Hopps.Me - Benedict Balzer
description: "#Gamedev And Randomness"
meta_description: >
  Small Website by Benedict Balzer showing of my games and other useful things.
baseurl: ""
#url: "http://localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
url: "https://hopps.me"
author: 
    name: Benedict Balzer

social: 
    github: devhopps
    twitter: dev_hopps
    youtube: channel/UCgIoIDUDdu5wApsED2XiIfg

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - .sass-cache

permalink: pretty

#Pagination
paginate: 5
paginate_path: "/blog/:num/"
