# Harmony Jekyll theme general configurations 

# Base URL
baseurl: 

# Site live URL
#url: http://gayan.me

# Localhost 
url: https://hopps.me
cdn: https://keycdn.hopps.me

harmony:
  name: Hopps.Me - Benedict Balzer
  description: "#Gamedev And Randomness"
  meta_description: > # 
   Small Website by Benedict Balzer showing of my games and other useful things.
  basetheme: theme-base-01
  author: 
    name: Benedict Balzer
    email: mail@hopps.me
    url: https://hopps.me

  google_analytics_key:

  social: 
    github: devhopps
    twitter: dev_hopps
    facebook: 
    gplus: 
    dribble: 
    pinterest: 

  show_disclaimer: true

markdown:    kramdown

highlighter: pygments 

permalink:        pretty

exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
    sass_dir: assets/css/_sass
    style: :compressed

gems:
    - jekyll-sitemap
